### ISSUE TITLE
Upgrade specific packages

### ISSUE THREAD

**Issue by itsmeboy0** [cokelid/ChocoButler#10]
Something like how [Brewlet](https://github.com/zkokaja/Brewlet) does it:
![Brewlet - Upgrade specific packages](https://github.com/zkokaja/Brewlet/blob/master/images/statusmenu-update.png?raw=true)

(Btw thanks for your project, been looking for something like Brewlet for Choco)

**Comment by cokelid** [comment]
Hmmm, yes interesting. You can "pin" packages in Chocolately to prevent them from being upgraded, and pinned packages are ignored by ChocoButler, so that was the use case I had in mind. But I see that this could be useful.
The downside of this would be that if you updated just one package, then you would keep getting alerts about the others, which could be a pain?
I'm not a mac guy so have never seen brewlet, but kinda glad ChocoButler looks similar, convergent evolution! Maybe I can steal some more ideas from it?!

**Comment by cokelid** [comment]
I've checked in changes to give a new packages menu, which shows the outdated packages and allows them to be individually upgraded. You should just be able to run the latest [chocobutler.ps1](https://github.com/cokelid/ChocoButler/blob/main/chocobutler.ps1) script and/or replace your existing one to test it out.
I'll do more testing and create a release later.
